---
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>

## Workshop Overview

This workshop will familiarize participants with the [R](http://cran.r-project.org/) language and the [RStudio](https://posit.co/products/open-source/rstudio/) environment for statistical computing. Both are freely available, multi-platform, programs for data wrangling, analysis, graphics, and project management. [R](http://cran.r-project.org/) provides a programming language that can easily be extended by the user, allows the user to produce publication-quality graphics, and is ubiquitous in statistical/quantitative courses around the world. This workshop does not require knowledge of advanced statistics methods and will not cover them in any detail. We will cover the basics of organizing, managing, and manipulating data, demonstrate basic applications, introduce programming, and review more advanced features such as data-driven documents and dynamic visualization.  


<br>
<br>

## Materials  
____

[Schedule](topics/R-schedule.html)

[R, The Basics & RStudio](topics/R-basics.html)

[Working with Data](topics/R-working-with-data.html)

[Programming: Functions, Loops, If/Else Statements](topics/R-programming.html)

[Data Visualization: R Graphics](topics/R-data-visualization.html)

[Data-Driven Documents: RMarkdown](topics/R-markdown.html)

[Dynamic Visualization: RShiny](topics/R-shiny.html)

[Using Artificial Intelligence with R: Coding Assistant](topics/R-AI.html)

<br>

____

<br>

##### ***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/RWorkshop/issues) page. Thanks!

<br>
<br>


###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***