---
title: "Central Tendency and Dispersion"
output: 
  flexdashboard::flex_dashboard:
    theme: spacelab
    source: embed
    smart: false
runtime: shiny
---

```{r include = FALSE}

x    <- seq( -5, 25, length=1000 ) # sequence from -15 to 30. 

```


=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}

sliderInput( "slider1m", label = h3( "Mean for Blue Distribution" ),  min = 0, max = max( x ), value = 0 )

sliderInput( "slider1sd", label = h3( "SD for Blue Distribution" ), min = 0, max = 10, value = 1 )

sliderInput( "slider2m", label = h3( "Mean for Green Distribution" ),  min = 0, max = max( x ), value = 5 )

sliderInput( "slider2sd", label = h3( "SD for Green Distribution" ), min = 0, max = 10, value = 2 )


```

Outputs
-------------------------------------

### Density Distributions for Variables

```{r}

renderPlot({

    plot.new()
    plot.window( xlim=c( min( x ), max( x ) ), ylim=c( 0, 0.5 ), xlab="", ylab="" )
    box()
    
    lines( x, dnorm( x, input$slider1m, input$slider1sd ), col="blue", type="l", lwd=2 )
    
    lines( x, dnorm( x, input$slider2m, input$slider2sd ), col="darkgreen", type="l", lwd=2 )

})

```   